- components/atoms/Button/Button.module.css
- components/atoms/Input/Input.module.css
- components/atoms/Input/Input.tsx
- components/molecules/Menu/Menu.module.css
- components/molecules/Menu/Menu.tsx
- components/molecules/Slide1/Slide1.module.css
- components/molecules/Slide2/Slide2.module.css
- components/molecules/Slide3/Slide3.module.css
- components/organisms/Carousel/Carousel.module.css
- components/organisms/Login/Login.module.css
- components/organisms/Login/Login.tsx
- components/organisms/Register/Register.module.css
- components/organisms/Register/Register.tsx
- src/app/globals.css
In Phase I, the variables were defined and modified in the carousel views and the login and registration views.
Also, small details that were found were corrected.
> CSS Variables Refactoring - Phase I

- components/organisms/CourseResources/CourseResources.module.css
- components/organisms/CourseResources/CourseResources.tsx
- components/organisms/DashboardUserWelcome/DashboardUserWelcome.module.css
- components/organisms/ResourcesAndVerses/ResourcesAndVerses.module.css
- src/app/globals.css
- Change of variables and colors
> Change variables view resources

- components/organisms/ForgetPassword/ForgetPassword.tsx
- components/organisms/Profile/Profile.tsx
- components/organisms/ResetPassword/ResetPassword.tsx
**1. Implementation of Password Characters and Requirements:**
> - A feature has been implemented that imposes specific requirements for passwords, improving the overall security of the system.
> - Now, when setting or changing passwords, certain criteria must be met, such as minimum length, inclusion of special characters, etc.
> - This improvement strengthens the security of user accounts and complies with security best practices.
> Des 214 implement stricter password requirements from recover password

- components/organisms/LearningPath/LearningPath.module.css
- components/organisms/LearningPath/LearningPath.tsx
- components/organisms/LearningPathProgress/LearningPathProgress.module.css
- components/organisms/LearningPathProgress/LearningPathProgress.tsx
- components/organisms/LearningPathVideoClass/LearningPathVideoClass.tsx
- components/organisms/TaringStart/TaringStart.tsx
- package-lock.json
In the LearningPahtProgress component, when selecting a topic, no selection was made or any particular style was applied, it was solved, and the selection of stars in the rating was also corrected, since the selection of them could not be removed
> Des 212 error in the selected topic

- components/atoms/Input/Input.tsx
- components/atoms/icons/addPhotoIcon/addPhotoIcon.module.css
- components/atoms/icons/closeModalIcon/CloseModalIcon.tsx
- components/atoms/icons/errorRegisterIcons/ErrorRegisterIcon.module.css
- components/atoms/icons/errorRegisterIcons/ErrorRegisterIcon.tsx
- components/organisms/ChangePasswordUser/ChangePasswordUser.module.css
- components/organisms/ChangePasswordUser/ChangePasswordUser.tsx
- components/organisms/Modal/Modal.module.css
- components/organisms/Modal/Modal.tsx
- components/organisms/Profile/Profile.module.css
- components/organisms/Profile/Profile.tsx
- components/organisms/Register/RegisterFormPassword/RegisterFormPassword.module.css
- components/organisms/Register/RegisterFormPassword/RegisterFormPassword.tsx
-Change of variables
-Change in some parts of the design
-Delete classes that were not being used
-Rename variables
> Des 218 profile

- .env
- components/atoms/Card/Card.module.css
- components/atoms/Card/Card.tsx
- components/organisms/Courses/Coures.tsx
- components/organisms/Courses/Courses.module.css
- components/organisms/LearningPath/LearningPath.tsx
- components/organisms/LearningPathProgress/LearningPathProgress.tsx
- components/organisms/LearningPathTitleClass/LearningPathTitleClass.module.css
- components/organisms/LearningPathTitleClass/LearningPathTitleClass.tsx
- components/organisms/LearningPathVideoClass/LearningPathVideoClass.tsx
- components/organisms/Path/Path.tsx
- components/organisms/Sidebar/Sidebar.tsx
- components/templates/Courses-template/CoursesTemplate.tsx
- src/app/(privateRoutes)/dashboard/courses/[courseName]/[courseId]/[lessonId]/[tema]/[indexVideo]/page.tsx
- src/app/(privateRoutes)/dashboard/courses/[courseName]/[courseId]/page.tsx
- src/app/(privateRoutes)/dashboard/courses/page.tsx
- src/app/(privateRoutes)/dashboard/path/course/[idtema]/[tema]/[idvideo]/page.tsx
- src/app/(privateRoutes)/dashboard/path/learningpath/page.tsx
- src/app/(privateRoutes)/dashboard/path/page.tsx
- src/app/globals.css
- src/types/next-auth.d.ts
- types/types/course.types.ts
- types/types/lessons.type.ts
- types/types/topic.type.ts
creation of the courses page in integration of the new courses database
> creation of the courses page in integration of the new courses database

- components/atoms/Input/Input.module.css
- components/atoms/Input/Input.tsx
- components/atoms/icons/checkRegisterIcon/CheckRegisterIcon.module.css
- components/atoms/icons/errorRegisterIcons/ErrorRegisterIcon.module.css
- components/organisms/ChangePasswordUser/ChangePasswordUser.module.css
- components/organisms/Register/Register.module.css
- components/organisms/Register/Register.tsx
- components/organisms/Register/RegisterFormPassword/RegisterFormPassword.module.css
- components/organisms/Register/RegisterFormPassword/RegisterFormPassword.tsx
-Change of variables
-Change in styles
-Fix styles
> Changes registration and password views

- .gitignore
- components/organisms/Path/Path.module.css
- components/organisms/Path/Path.tsx
Changes were made to the organization of the content so that the titles did not overlap
> Des 251 path view deuteronomio

- components/organisms/Assessment/AssessmentMain/AssessmentMain.module.css
- components/organisms/Assessment/AssessmentMain/AssessmentMain.tsx
-Application of variables
-Change of names in classes
> change variables assessmentMain

- components/organisms/Assessment/AssessmentMain/AssessmentMain.module.css
- components/organisms/Assessment/AssessmentTitleSubtitleBackground/AssessmentTitleSubtitleBackground.module.css
- components/organisms/Assessment/AssessmentTitleSubtitleBackground/AssessmentTitleSubtitleBackground.tsx
-Application of variables
-Change of names in classes
-Creation and change of background image
> Change assessment view

- components/organisms/LearningPath/LearningPath.tsx
- components/organisms/LearningPathVideoClass/LearningPathVideoClass.tsx
- components/organisms/Path/Path.tsx
- src/types/next-auth.d.ts
- types/types/lessons.type.ts
- types/types/topic.type.ts
Des 244 create progresss video status from lessons completed to handle siguiente button
> Des 244 create progresss video status from lessons completed to handle siguiente button

- components/organisms/Profile/Profile.module.css
- components/organisms/Profile/Profile.tsx
In this task, the way in which the user's profile photo is displayed when selecting it was updated so that the user can preview the final result of the photo they have chosen.
> Preview of user selected profile photo or updated profile photo

- components/organisms/Register/Register.tsx
- components/organisms/Register/RegisterFormInformation/RegisterFormInformation.tsx
validacion en formulario como mensajes correstos desde el back-end y no impouestos por el front como se venia haciendo
> Des 263 register the next button doesnt work for a second try after missing any input exept email input

- components/organisms/DashboardUserWelcome/DashboardUserWelcome..tsx
- components/organisms/DashboardUserWelcome/DashboardUserWelcome.module.css
Implemented a conditional check to recommend the first course video to users who have never viewed a video. This recommendation is displayed when a user has no viewing history.
- Added a conditional check for users with no video viewing history.
- If the user has never viewed a video, recommend the first course video available on the platform.
- Implemented a skeleton loader for the video title to provide a better user experience during loading.
> Des 270 dashboard the continue in your lesson option redirects to the first video if the user has not watched any video

- components/organisms/Register/RegisterFormPassword/RegisterFormPassword.module.css
Change color and background to the button "Cambiar contraseña"
> Changing button style

- components/organisms/Profile/Profile.module.css
- components/organisms/Profile/Profile.tsx
Save profile photo to database
> Save profile photo to database

- components/organisms/Register/Register.module.css
- components/organisms/Register/RegisterFormPassword/RegisterFormPassword.module.css
- Change in colors
- Specificity added
> Des 282 crear cuenta button hover style

- components/organisms/Assessment/AssessmentQuestions/AssessmentQuestions.module.css
- components/organisms/Assessment/AssessmentQuestions/AssessmentQuestions.tsx
Change of styles
Change in class names
> Change styles

- components/organisms/DashboardUserWelcome/DashboardUserWelcome.module.css
Added white color to container
> Color added

- components/organisms/LearningPath/LearningPath.module.css
- components/organisms/Profile/Profile.module.css
- Added color to profile view background
- Added a background image for the "learningPathTitleClass-container" view
> Changes in background styles

- components/organisms/Register/RegisterFormPassword/RegisterFormPassword.module.css
- components/organisms/Register/RegisterFormPassword/RegisterFormPassword.tsx
Added logic to determine which styles to apply to each button
> Added logic

- components/molecules/Menu/Menu.module.css
- components/molecules/Menu/Menu.tsx
- components/organisms/Register/RegisterFormPassword/RegisterFormPassword.tsx
-I changed the logo image
-I added styles
-I eliminated 2 repeated lines of code (because the project did not run)
Before: 
Now:
> Changing logo

- components/organisms/Sidebar/Sidebar.tsx
- src/app/(privateRoutes)/dashboard/admin/profile/page.tsx
- src/middleware.ts
- src/types/next-auth.d.ts
for those users who are not administrators and do not show visibility of the admin button
> restrict access to the dashboard/admin/* path
